### ISSUE TITLE
outlook live calendar showing different dates

### ISSUE THREAD

**Issue by govardhan5** [AnandChowdhary/calendar-link#154]
It seems like the startdt and enddt provided by us in query param is not getting triggered instead it is taking the current date.  

Below is the the event I tried to create.

https://outlook.live.com/calendar/0/deeplink/compose?startdt=20200812T000000&enddt=20200813T120000&subject=Hello%20World&body=Hello%20World.

**Comment by AnandChowdhary** [comment]
Thanks for opening this issue, @govardhan5. Perhaps Outlook changed some of the parameter names when I updated the UI, I'll have a closer look.

**Comment by govardhan5** [comment]
Thanks for the response @AnandChowdhary . Can you please let me know approximate estimation date to fix this issue if possible?

**Comment by AnandChowdhary** [comment]
Honestly, my plate is a little full at the moment. I might have some time this weekend to look into this, otherwise I'll make sure I get into it next week.

**Comment by govardhan5** [comment]
Thanks for the response @AnandChowdhary

**Comment by webaware** [comment]
The date/time format has changed. 

It now no longer accepts YYYYMMDD\THHmmss, 
must now be YYYY-MM-DD\THH:mm:ss

Like so:

https://outlook.live.com/calendar/0/deeplink/compose?startdt=2020-08-12T00:00:00&enddt=2020-08-13T12:00:00&subject=Hello%20World&body=Hello%20World

**Comment by AnandChowdhary** [comment]
That's right, thanks! We're discussing this in https://github.com/InteractionDesignFoundation/add-event-to-calendar-docs/pull/10 and I'll push an update to this repo soon.

**Comment by webaware** [comment]
Ah, cool. I did look at that project but somehow missed the PR / issue. Good to see the docs will get the update too! :+1:

**Comment by paulboocock** [comment]
Hi @AnandChowdhary I see that https://github.com/InteractionDesignFoundation/add-event-to-calendar-docs/pull/10 is merged. Any rough ETA on when it might be fixed in this repo?

**Comment by AnandChowdhary** [comment]
Feel free to pick this up! I'll need more time to get to it; though it's trivial, my hands are pretty full these days.

**Comment by suit0r** [comment]
an updates on this? the package works great otherwise, but the outlook/office365 links don't receive correct dates, so it defaults to today. i'm passing it an `.toISOstring()`, but i tried  a bunch of things, and nothing worked. google works fine, with ISO. 
this is the ics in comparison:
```BEGIN:VCALENDAR
VERSION:2.0
BEGIN:VEVENT
URL:MYURL.com
DTSTART:20200830T160000Z
DTEND:20200830T173000Z
SUMMARY:My meeting
DESCRIPTION:Description here
LOCATION:Some location
END:VEVENT
END:VCALENDAR
```

**Comment by paulboocock** [comment]
I've been meaning to submit a PR for this but if you want a quick fix in your application, I've been doing this:

```
const outlook = calendar.outlook(event);
console.log('Outlook: ' + outlook.replace(/(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})/g, '$1-$2-$3T$4:$5:$6')); 
```

**Comment by suit0r** [comment]
thanks a lot. works on both outlook and office calendars.

**Comment by AnandChowdhary** [comment]
> I've been meaning to submit a PR for this but if you want a quick fix in your application, I've been doing this:
> 
> 
> 
> ```
> 
> const outlook = calendar.outlook(event);
> 
> console.log('Outlook: ' + outlook.replace(/(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})/g, '$1-$2-$3T$4:$5:$6')); 
> 
> ```

Would love a PR!

**Comment by AnandChowdhary** [comment]
The replacement has been added in v1.3.1, thanks to @paulboocock!

**Comment by jonwhuang** [comment]
The outlook/office365 fix doesn't seem to take timezone into account.

If I pass in `20200924T170000Z` to `20200924T180000Z` for start/end times, it shows different values for Google vs Outlook.

Google converts the times to the user's timezone while outlook seems to use 5-6PM.

**Comment by frysztak** [comment]
I'm still experiencing this issue at version 2.0.11. Instead of `YYYY-MM-DD`, `YYYYMMDD` format is used
