### ISSUE TITLE
unable to generate event if the user is not loggedin to outlook account  before selecting outlook online

### ISSUE THREAD

**Issue by govardhan5** [AnandChowdhary/calendar-link#161]
once user select the outlook online option after redirection it will ask for outlook account credentials and after giving the credentials an empty event is generated without any details.

If the user already loggedin to outlook account and when the user select outlook online option from th application  then after redirection an event is generated with the correct data. So in this scenario it is working as expected.

**Comment by govardhan5** [comment]
Hi @AnandChowdhary  is there any update on this issue.

**Comment by AnandChowdhary** [comment]
Unfortunately not yet. Once I've pushed the new Outlook URL, I'll make sure I do extensive testing with this use case. I'll keep this issue open for a few more days.

**Comment by AnandChowdhary** [comment]
Can you test this with v1.3.1?

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by RHellenes** [comment]
I tested this with the Office365 link an that one still works after I log in.  
[Office365 link](https://outlook.office.com/calendar/0/deeplink/compose?body=Hvordan%E2%80%89bruke%E2%80%89data%E2%80%89til%E2%80%89%C3%A5%E2%80%89f%C3%A5%E2%80%89nye%E2%80%89kunder%E2%80%89og%E2%80%89bedre%E2%80%89kundedialog%3F&enddt=2020-11-12T10:45:00&path=%2Fcalendar%2Faction%2Fcompose&rru=addevent&startdt=2020-11-12T10:00:00&subject=Webinar%E2%80%89%7C%E2%80%89Finn%E2%80%89nye%E2%80%89kunder%E2%80%89med%E2%80%89riktig%E2%80%89data%E2%80%89%E2%80%93%E2%80%89Bas): 
[Outlook Link ](https://outlook.live.com/calendar/0/deeplink/compose?body=Hvordan%E2%80%89bruke%E2%80%89data%E2%80%89til%E2%80%89%C3%A5%E2%80%89f%C3%A5%E2%80%89nye%E2%80%89kunder%E2%80%89og%E2%80%89bedre%E2%80%89kundedialog%3F&enddt=2020-11-12T10:45:00&path=%2Fcalendar%2Faction%2Fcompose&rru=addevent&startdt=2020-11-12T10:00:00&subject=Webinar%E2%80%89%7C%E2%80%89Finn%E2%80%89nye%E2%80%89kunder%E2%80%89med%E2%80%89riktig%E2%80%89data%E2%80%89%E2%80%93%E2%80%89Bas)(not tested)

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
