### ISSUE TITLE
outlook online event is not generated in mobile devices

### ISSUE THREAD

**Issue by govardhan5** [AnandChowdhary/calendar-link#162]
unable to create outlook online event in mobile devices either in Android or in IOS.

**Comment by govardhan5** [comment]
Hi @AnandChowdhary  is there any update on this issue?

**Comment by AnandChowdhary** [comment]
I'm unable to reproduce this issue. Do you think you can add more details about what specifically is going wrong? I'm assuming you're using the new URL, not the older one?

**Comment by govardhan5** [comment]
Thanks for the response @AnandChowdhary . Yes I am using the new URL.

In the mobile devices when i select the outlook online option from my application it is redirecting to the outlook account and after giving the credentials I am unable to see the event. I am attaching the screenshot below. 
The url I observed after redirection is the below one.
https://outlook.live.com/calendar/0/view/agenda#startdt=2020-09-09T00%3a00%3a00&enddt=2020-09-10T00%3a00%3a00&subject=Trip+to+New+York&body=Trip+to+New+York&location=&nlp=1&RpsCsrfState=da95d229-a611-5268-0d3b-9126eecd9b68&wa=wsignin1.0 in the mobile device
![mobile_outlookonline](https://user-images.githubusercontent.com/63655465/80525115-b5e77f00-895e-11ea-8969-1991cddee496.jpg)

Please let me know if you have any questions.

**Comment by AnandChowdhary** [comment]
Thanks! This seems like it's an issue with the Outlook web app, not the link, but I'll do some more testing. If that is the case, perhaps we should open a bug with Microsoft.

**Comment by AnandChowdhary** [comment]
Can you test this with v1.3.1?

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
