### ISSUE TITLE
Is there a more advanced example of duration property containing more than one unit type?

### ISSUE THREAD

**Issue by RHellenes** [AnandChowdhary/calendar-link#177]
**Docs says:**
|Property|Description |Allowed values
|--|--|--|
|duration | Event duration | Array with value (Number) and unit (String)|

e.g.: `duration: [3, "hour"]`

&nbsp;

**Case:**
What if the duration is not neither just hours or minutes e.g. 1 hour and 40 minutes. How should the data be formatted?  `duration: [ [1, "hour"], [40, "minute"] ]`?

**Comment by RHellenes** [comment]
**Re:**
Converting the time difference to be in just minutes i.e. 1 hour and 40 minutes = 100 minutes seems to do the trick.

**Comment by AnandChowdhary** [comment]
I think converting to the minutes is the way to go, no point making it more complicated with nested array inputs etc.
