### ISSUE TITLE
Incorrect Yahoo All Day Calendar URL

### ISSUE THREAD

**Issue by jonsaw** [AnandChowdhary/calendar-link#190]
Yahoo supports the all-day flag by appending `&dur=allday` in the URL.

Example:
https://calendar.yahoo.com/?desc=Description&in_loc=Malaysia&st=20200730&title=Test%20title&v=60&dur=allday

Will correctly generate all-day calendar event:
![Screenshot 2020-07-17 at 7 57 32 PM](https://user-images.githubusercontent.com/1572333/87783972-0ee0f800-c868-11ea-9f2b-3bdc753216f5.png)

`&et=20200731` is not needed

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by paddlepaw** [comment]
Hello, in addition to being able to use dur=allday could we have the option to use dur=HHMM?  It seems Yahoo has a long standing bug where it does not convert the UTC time to the local user's timezone.  So if I'm -0500 eastern and I pass 2:45PM to the calendar-link lib the link will be: https://calendar.yahoo.com/?desc=&et=20201201T194500Z&in_loc=kellogg%27s%20ctr&st=20201201T130000Z&title=Jared%27s%20Calendar%20Event&v=60 which is correct but Yahoo sees T194500Z and converts it to 7:45 PM.  

Yahoo's dur parameter only accepts 99 hours and 99 minutes max which does not support everything but it'd be nice for smaller events which are probably more common.  I'd rather have something that works for most situations and if I know I'm going over the max values I'd just omit the link in that case.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
