### ISSUE TITLE
spaces converted to plus sign in outlook.com

### ISSUE THREAD

**Issue by ruiLemosCode** [AnandChowdhary/calendar-link#219]
Using the new outlook.com link `https://outlook.live.com/calendar/0/deeplink/compose?` all spaces are being converted into plus sign. This happen in the location, description and title of the event.

This is weird because the url is being correctly encoded (the spaces are being converted to `%20` as they should), but then when outlook.com open all the spaces are plus signs.

I tried this with other plugin and happens the same, if using the new link. This is a non issue with the old link (`https://outlook.live.com/owa/?path=/calendar/action/compose`).

**Comment by AnandChowdhary** [comment]
Seems like the only workout at this moment is to use thin spaces, which I'm not a fan of. Let's continue the discussion here: https://github.com/InteractionDesignFoundation/add-event-to-calendar-docs/issues/20.

**Comment by vyas0189** [comment]
I fixed this issue by doing this `outlook(event).replace("&rru=addevent", "")`

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by marcusx2** [comment]
Are you kidding me? @AnandChowdhary the bot is closing issues that shouldn't be closed! Definitely misbehaving!
