### ISSUE TITLE
Request for UMD package for easy implementation in projects without build pipeline

### ISSUE THREAD

**Issue by LeHvass** [AnandChowdhary/calendar-link#220]
I am currently working on a small front end project without a build pipeline.

The front end itself is unfortunately limited to a single, self-contained HTML page (and any plugins hosted on CDNs).

For this use case, it would be fantastic to have a UMD package that would allow us to simply include the package with a <script src=""></script> and start calling the package methods.

What are your thoughts on something like this?

P.S. Feel free to correct me if I'm missing something, in terms of how this can perhaps already be accomplished without the use of Gulp, Webpack and the like.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
