### ISSUE TITLE
Automatic localhost URL

### ISSUE THREAD

**Issue by fidelman** [AnandChowdhary/calendar-link#227]
Hello,

I pass an event without a URL, but [`ics` function inserts `localhost`](https://github.com/AnandChowdhary/calendar-link/blob/master/index.ts#L40) anyway. Can you please describe a case, where it is necessary to always add `document.URL`?

Unfortunately, it brings not the best UX
<img width="478" alt="Screenshot 2020-10-15 at 17 13 06" src="https://user-images.githubusercontent.com/15198653/96149519-b32b1700-0f09-11eb-9119-6a3292e063db.png">

Thank you

**Comment by AnandChowdhary** [comment]
You're right, it makes absolute sense to generate ICS files without a URL. Can you make a PR?

**Comment by fidelman** [comment]
> You're right, it makes absolute sense to generate ICS files without a URL. Can you make a PR?

yes, fo sure. Thanks
