### ISSUE TITLE
issues with ICS

### ISSUE THREAD

**Issue by nosizejosh** [AnandChowdhary/calendar-link#232]
@AnandChowdhary  I am trying to send generated links via email template  and all the other links works ( google, outlook etc) except the ics.

In the received email, the ics doesn't show up as a clickable link and an inspection of the sent email shows that the entire href doesn't show from the the receiver's inbox, making it impossible to click to get the download ics dialogue. 

Below is an example of the link data:text/calendar;charset=utf8,BEGIN:VCALENDAR%0AVERSION:2.0%0ABEGIN:VEVENT%0AURL:http%3A%2F%2Flocalhost%3A3000%2F%40newuser%2Focta%0ADTSTART:20201023T090000Z%0ADTEND:20201023T091000Z%0ASUMMARY:octa%0ADESCRIPTION:description%20not%20set%20yet%0AEND:VEVENT%0AEND:VCALENDAR%0A 
generated and which is clickable from dev console.

I tried to use your decode method above but that results in 
BEGIN:VCALENDAR
VERSION:2.0
BEGIN:VEVENT
URL:http://localhost:3000/@newuser/octa
DTSTART:20201023T094500Z
DTEND:20201023T095500Z
SUMMARY:octa
DESCRIPTION:description not set yet
END:VEVENT
END:VCALENDAR.

This is how i am sending the links via the email template:
```
<a href="{{addToGoogleCalendarLink}}" style="text-decoration:underline">Google</a> |
 <a href="{{addToICSCalendarLink}}" download style="text-decoration:underline">iCal</a> | 
 <a href="{{addToYahooCalendarLink}}" style="text-decoration:underline">Yahoo!</a> |
 <a href="{{addToOutlookCalendarLink}}" style="text-decoration:underline">Outlook</a> |
 <a href="{{addToOffice365CalendarLink}}" style="text-decoration:underline">Office365</a>
``` 

What I am trying to achieve is to get the link clickable from the email inbox so a user can add to their calendar. Can you please check what i am doing wrong?

Thanks

**Comment by AnandChowdhary** [comment]
I'm closing this since we're having the discussion in #208.
