### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by marcusx2** [AnandChowdhary/calendar-link#286]
1. The description doesn't say what are the duration units available. By searching the issues and the web, I found there are at least: _hour_, _minute_, and _day_. Are there any others?
2. Between _end_, _duration_, and _allDay_ fields, which one them takes priority? Are they mutually exclusive or can I use all of them at once(even though it doesn't actually make sense)? For example, can I have the duration field saying 2 hours, but have the allDay field set to true? Can I have the duration field and the end field even if they don't match? Do I get errors if I use all of them at once or does it simply generate a calendar event with potentially contradicting data?

**Comment by marcusx2** [comment]
Regarding my first question, upon further investigation on the source I found these units: `millisecond, second, minute, hour, day, week, month, quarter, year`. I tested all of them, on all calendars. `millisecond` and `second` don't work, simply because the calendars don't have enough precision I suspect. However, `quarter` doesn't work as well, and I suspect this one should.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by marcusx2** [comment]
...

**Comment by Heatmanofurioso** [comment]
It would be great to get some response on this
