### ISSUE TITLE
busy's property value ignored.

### ISSUE THREAD

**Issue by marcusx2** [AnandChowdhary/calendar-link#287]
I set the `busy `property to false, but when the calendar event is created, `busy `is true. I tested this on the google calendar and yahoo.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by marcusx2** [comment]
lWell don't close it because it wasn't fixed mr. bot lol

**Comment by JenaeStuder** [comment]
I'm also having this issue, regardless of the boolean's value, the generated link automatically sets my calendar to "busy". :/

**Comment by marcusx2** [comment]
It seems that this repo was abandoned, sadly.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by marcusx2** [comment]
Don't close it you stupid bot!

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
