### ISSUE TITLE
If url is set to empty string, it still defaults to document.URL.

### ISSUE THREAD

**Issue by marcusx2** [AnandChowdhary/calendar-link#288]
I don't want the URL field to be filled in. If I set `url = ""`, it's **still** filled in with `document.URL`. To avoid the url completely I need an empty space in the url: `url = " "`. Is this intentional? It looks like a bug to me. If you want the url to be filled in with `document.URL`, you should check if the user set it to `undefined`, `null`, or not set at all. But the empty string should mean that the user wants the URL field to be empty, don't you think? Tested on iOS Safari.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by marcusx2** [comment]
...

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by marcusx2** [comment]
No.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
