### ISSUE TITLE
yahoo's calendar event is created with wrong end date

### ISSUE THREAD

**Issue by marcusx2** [AnandChowdhary/calendar-link#290]
Start date is `2021-04-02 18:00:00`, End date is `2021-04-02 23:00:00`. On yahoo the calendar event is created with end date `2021-04-03 02:00:00`. I tried using the duration argument, [5, 'hour'] with same start date, it didn't work either. No problems with the other calendars.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by marcusx2** [comment]
...........

**Comment by agaripian** [comment]
We have the same issue with Yahoo any updates on this?

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by marcusx2** [comment]
No you won't. I will fight you until the end of times stupid bot.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
