### ISSUE TITLE
Help needed: Production version generates a different link than the local version

### ISSUE THREAD

**Issue by RHellenes** [AnandChowdhary/calendar-link#296]
Hi – I don't know if this is a bug with this package, or if it has something to do with my setup. 

### The issue 

The desired dates are **22. aug. 2021 08:00 - 25. aug. 2021 15:00**

As the title says, the links that are generated in my local version is working as expected: 

Local link: [https://calendar.google.com/calendar/render?action=TEMPLATE&dates=20210822T060000Z%2F20210825T130000Z&details=Description&text=Title](https://calendar.google.com/calendar/render?action=TEMPLATE&dates=20210822T060000Z%2F20210825T130000Z&details=Description&text=Title)

But the link in production adds 2 hours at both start and end: 

Production link: [https://calendar.google.com/calendar/render?action=TEMPLATE&dates=20210822T080000Z%2F20210825T150000Z&details=Description&text=Title](https://calendar.google.com/calendar/render?action=TEMPLATE&dates=20210822T080000Z%2F20210825T150000Z&details=Description&text=Title)

### Things that I have tried: 

- Checked that the in-data is the same on both places (they are): 2021-08-22T06:00:00.000Z
- Tried to uninstall this package, upload it to the production, then reinstall it, then upload it to production again (Didn't help).
- The production server and I are both in the same time zone. 

Version: calendar-link: 2.0.8

**Comment by RHellenes** [comment]
This happens on all calendars

**Comment by RHellenes** [comment]
Update: The component works before 12.00 (24h time format) — After 12.00 it movess the event  +2 hours in time, and still only in production. 

The start date I use is the same both locally and in production 

Does this make any sense to you @AnandChowdhary?

**Comment by AnandChowdhary** [comment]
No, that's very weird indeed... We do convert the date stamps into UTC (https://github.com/AnandChowdhary/calendar-link/blob/89b3d0629d6791cc38332c7245bc60fe8b736d6b/src/index.ts#L15) but we don't do anything special with the `12`.

**Comment by marcusx2** [comment]
@AnandChowdhary Are my issues being ignored? I created many issues long before this one and nobody replied.

**Comment by AnandChowdhary** [comment]
> @AnandChowdhary Are my issues being ignored? I created many issues long before this one and nobody replied.

I promise it's not personal! There are several issues I still need to work through in this library. I'm overwhelmed with @koj-co work these days, but I'd be happy to accept PRs for any of these issues. 😄

**Comment by RHellenes** [comment]
I solved my issue — And it was on my end, not with this package. 

### Solution:

I had to import and set a timezone to my moment.js module and strictly specify it.
