### ISSUE TITLE
Outlook's link doesn't add the guests to the invite section.

### ISSUE THREAD

**Issue by mutebironald** [AnandChowdhary/calendar-link#320]
calendar-link@2.0.13
Browser: Chrome@88

Data passed
eventData = {
		title: "topic",
		description: https://localhost:3000/zvhb0egh,
		start: startDate,
		duration,
		guests : [ "test@test.com" ]
};

Generated URL:  https://outlook.live.com/calendar/0/deeplink/compose?body=https%3a%2f%2flocalhost%3a3000%2fzvhb0egh&enddt=2021-02-24T10%3a07%3a52+00%3a00&path=%2fcalendar%2faction%2fcompose&startdt=2021-02-24T10%3a07%3a08+00%3a00&subject=topic

Notice, the invite attendees section is still empty. I would expect the email `test@test.com` to be there
![outlook](https://user-images.githubusercontent.com/39955301/108985028-9fef3b80-76a1-11eb-816d-88b0f74fe271.PNG)

**Comment by haveaguess** [comment]
Here's an example that works just to prove it is possible : 

https://outlook.live.com/calendar/0/deeplink/compose?startdt=2021-03-26T13%3A48%3A00Z&enddt=2021-03-26T14%3A03%3A00Z&subject=Ben%26%2332%3Btest%26%2332%3Bpod&location=https%3A%2F%2Fstaging-connect4.herokuapp.com%2Froom%2FdS2FzdNygtwa6GgC6&body=%3Cbr%3EYou%26%2332%3Bcan%26%2332%3Bjoin%26%2332%3Bhere%26%2332%3B%3A%26%2332%3Bhttps%3A%2F%2Fstaging-cct4.herokuapp.com%2Froom%2FdS2FzdNygtwa6GgC6%26%2332%3B%3Cbr%3E%3Cbr%3E%5BUse%26%2332%3BChrome%26%2332%3BBrowser%26%2332%3Bon%26%2332%3Bfull-size%26%2332%3Bscreen%26%2332%3Bfor%26%2332%3Bbest%26%2332%3Bresults%5D&to=ritch%40gmail.com%2Ctestie%2Bcto3%40gmail.com%2Cchloe92%40gmail.com%2Cgamd%40hotmail.com&allday=false&uid=1616766594414

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by haveaguess** [comment]
I wouldn't say this is stale, just not fixed!

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by godilite** [comment]
I have same issue, @haveaguess were you able to fix this?

**Comment by haveaguess** [comment]
I ended up building on the URL format above, and forking [a react project](https://github.com/CultureHQ/add-to-calendar) to get some code working for me

**Comment by godilite** [comment]
I am using this project in dart could you please explain how you implemented that?

**Comment by godilite** [comment]
Like what parameters make up the URL?

**Comment by haveaguess** [comment]
> Like what parameters make up the URL? Cos for me it's not working for all calendar types, not just outlook

Sure I built against this document IIRC

https://interactiondesignfoundation.github.io/add-event-to-calendar-docs/services/outlook-web.html
