### ISSUE TITLE
Sign-in with Office365 user when using Outlook link

### ISSUE THREAD

**Issue by bennytieu** [AnandChowdhary/calendar-link#324]
When using the Outlook link, the user is redirected to https://outlook.live.com/owa/. However, it seems like an Office365 user is still able to login using their account in that link, which will redirect you to your mail inbox instead of the calendar event.

For me, this sounds like a problem on Outlook's end, since they should prompt you an error when trying to do this. Because, doing the other way around will give you an error, i.e. using the Office365 link (https://outlook.office.com/owa/) and trying to sign in with your personal Outlook account will prompt you _"You can't sign in here with a personal account. Use your work or school account instead."_.

**Comment by pfilipsson** [comment]
We have had to disable our links to Office365 calendars for the same reason. 

+1

**Comment by haveaguess** [comment]
In our implementation of a calendar link generator we've just broken it out as three buttons now : 

![image](https://user-images.githubusercontent.com/85821/112989724-1f6aa180-915d-11eb-9215-2642b7205d8d.png)

This is our hacked together fork of a ReactJS calendar https://github.com/connect4app/add-to-calendar

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
