### ISSUE TITLE
Angular 11.2.x gives CommonJS or AMD dependencies warning with calendar-link

### ISSUE THREAD

**Issue by Heatmanofurioso** [AnandChowdhary/calendar-link#335]
When using calendar-link with angular 11.2.x, we get the following warning upon doing `ng serve`.

`Warning: D:\Git\Project\src\app\core\my.component.ts depends on 'calendar-link'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
`

CommonJS dependencies are being unadvised for Angular starting from versions 10.x.

Info:
Angular version: 11.2.9
Angular cli version: 11.2.8
calendar-link version: 2.0.16

More information here:
[Configuring CommonJS dependencies](https://angular.io/guide/build#configuring-commonjs-dependencies)

**Comment by Ruslancic** [comment]
Not Only...
I have this error: 
`Error: node_modules/calendar-link/dist/interfaces.d.ts:1:8 - error TS1259: Module '"C:********/node_modules/dayjs/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

1 import dayjs from "dayjs";
         ~~~~~

  node_modules/dayjs/index.d.ts:3:1
    3 export = dayjs;
      ~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.`

**Comment by Heatmanofurioso** [comment]
@Ruslancic That seems to be a different issue though.

You should probably open a dedicated issue for it.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by Heatmanofurioso** [comment]
Ping

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by Heatmanofurioso** [comment]
Ditto...

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by Heatmanofurioso** [comment]
Anyone?

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by Heatmanofurioso** [comment]
So I'd assume the project is abandoned?

**Comment by dcerniglia** [comment]
I'm curious to see if there will be a response to this.

**Comment by Ruslancic** [comment]
> I'm curious to see if there will be a response to this. @Heatmanofurioso Is it safe to assume you're still having this issue? I was getting ready to use this in an Angular 13 project, but now I'm hesitating

I think, this project is abandoned....

**Comment by Heatmanofurioso** [comment]
@dcerniglia @Ruslancic I myself stopped using it, since support really seemed to be abandoned.
There's a few similar more recent projects roaming around NPM though. You are probably better off giving one of them a try

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by AnandChowdhary** [comment]
I'm not an Angular expert and I've got no idea what the issue means :( Were you able to figure out what's wrong and perhaps make a PR?

**Comment by Ruslancic** [comment]
> I'm not an Angular expert and I've got no idea what the issue means :( Were you able to figure out what's wrong and perhaps make a PR?

Just  change the file `calendar-link/dist/interfaces.d.ts` from 

> import dayjs from "dayjs";

to

> import * as dayjs from "dayjs";

**Comment by AnandChowdhary** [comment]
Aah, thanks @Ruslancic! Can you please make a PR? Would love to have you as a contributor!

**Comment by ilari-makimattila** [comment]
Hello. I bumped into this while cleaning out hacks from our codebase. I created the PR.
