### ISSUE TITLE
Node/TS: cannot use module without esModuleInterop 

### ISSUE THREAD

**Issue by spock123** [AnandChowdhary/calendar-link#337]
Hi, I'm trying to use this module in my project (Node/Typescript) but compiler gives this error:

`import { google } from 'calendar-link';`

`node_modules/calendar-link/dist/interfaces.d.ts:1:8 - error TS1259: Module '"/Users/lrj/project/fastorder/backend/node_modules/dayjs/index"' can only be default-imported using the 'esModuleInterop' flag`

I can't set esModuleInterop to true, that would break 1000 modules in my backend application.

Thanks

**Comment by liemdoan** [comment]
Hi, This issue persists on v2.1.1.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
