### ISSUE TITLE
Node 14: targets must start with "./"

### ISSUE THREAD

**Issue by spock123** [AnandChowdhary/calendar-link#338]
Using Node 14. / Typescript 3.7 (esInterop true) I am met with:

`Error: Invalid "exports" main target "dist/index.modern.js" defined in the package config /Users/lrj/project/fastorder/backend/node_modules/calendar-link/package.json; targets must start with "./"`

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
