### ISSUE TITLE
This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

### ISSUE THREAD

**Issue by Ruslancic** [AnandChowdhary/calendar-link#357]
I have this error: 

> Error: node_modules/calendar-link/dist/interfaces.d.ts:1:8 - error TS1259: Module '"C:********/node_modules/dayjs/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag
> 
> 1 import dayjs from "dayjs";
>          ~~~~~
> 
>   node_modules/dayjs/index.d.ts:3:1
>     3 export = dayjs;
>       ~~~~~~~~~~~~~~~
>     This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.`

So i change the file `node_modules/calendar-link/dist/interfaces.d.ts` from 

> import dayjs from "dayjs";

to

> import * as dayjs from "dayjs";

and all working fine.....hope so...

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
