### ISSUE TITLE
Source map references files that are not found in published NPM package

### ISSUE THREAD

**Issue by Poky85** [AnandChowdhary/calendar-link#405]
When generated source maps are loaded in my project I get following warnings:

```
Could not load source file "../src/index.ts" in source map of "../node_modules/calendar-link/dist/index.js".
Could not load source file "../src/utils.ts" in source map of "../node_modules/calendar-link/dist/utils.js".
```

This is because `dist/index.js.map` includes reference `"../src/index.ts"`. This file is not part of NPM package (it doesn't include `/src` folder at all). Similarly `dist/utils.js.map` includes  reference`"../src/utils.ts"`.

Could we publish `/src` folder to NPM?

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
