### ISSUE TITLE
Escape comma and newline in LOCATION for iCal

### ISSUE THREAD

**Issue by mrleblanc101** [AnandChowdhary/calendar-link#455]
LOCATION field in iCal should have comma and newline escaped.
Ex:
```
197 Route Pénélope,
Saint-Corrine-de-Sales, Île-du-Prince-Édouard, N9Z9F3
Aruba
```
Will only display `197 Route Pénélope` (stops at first comma).

<img width="425" alt="Capture d’écran, le 2022-06-01 à 12 05 26" src="https://user-images.githubusercontent.com/17392251/171449515-1eb6c08c-0a29-4334-97a9-6e829cac98f9.png">

But if I change it like this, it works.
```
197 Route Pénélope\,\nSaint-Corrine-de-Sales\, Île-du-Prince-Édouard\, N9Z9F3\nAruba
```
<img width="429" alt="Capture d’écran, le 2022-06-01 à 11 59 44" src="https://user-images.githubusercontent.com/17392251/171449373-91b1be99-34ac-4dd5-a646-68cdf6f89d19.png">

I've manually escaped the newline and comma, but now it cause issue in Google Calendar and Outlook web app as those don't need to escaping.

![Capture d’écran, le 2022-06-01 à 12 04 29](https://user-images.githubusercontent.com/17392251/171449689-f1d7cc6d-798b-4e68-b8c6-8840c77cca68.png)
![Capture d’écran, le 2022-06-01 à 12 06 21](https://user-images.githubusercontent.com/17392251/171449691-bc50f9af-f817-477e-a62c-194bd1c5bb9e.png)

**Comment by AnandChowdhary** [comment]
Happy to review a PR!

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by mrleblanc101** [comment]
Really ?

**Comment by AnandChowdhary** [comment]
Am I right? Robots I tell you :)

Happy to reopen if you're up for a PR!
