### ISSUE TITLE
Calendars not displaying the correct time on outlook mobile website

### ISSUE THREAD

**Issue by ACodingProphet** [AnandChowdhary/calendar-link#462]
For outlook.live desktop everything is fine, but for mobile it creates the event with the correct date, however it doesn't read the time. It is showing the event duration to be the entire day. 

Here is the link generating:
https://outlook.live.com/calendar/0/deeplink/compose?allday=false&enddt=2022-06-17T16%3A30%3A00%2B00%3A00&path=%2Fcalendar%2Faction%2Fcompose&rru=addevent&startdt=2022-06-17T13%3A00%3A00%2B00%3A00&subject=Test

Here is what it looks like on the desktop website with the correct time: 

![EventCreatedThroughWeb](https://user-images.githubusercontent.com/108023648/175113030-80be2793-abff-4016-8a2d-ada7599489d8.PNG)

Here is what the mobile version is showing, with the day long duration:

![EventCreationThroughMobileSite](https://user-images.githubusercontent.com/108023648/175113398-f2909de2-d818-4607-946a-efab9af40470.PNG)

Version:
 "calendar-link": "^2.2.0",

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by thomasrm** [comment]
Hi,

I'm having the exact same issue on mobile only. Time is ignored and a full day event is created. The weirdest thing is that it only happens on mobile. Works perfectly on desktop. 
Did you find a workaround?

Thanks

**Comment by dirkkelderman** [comment]
Hey there,

I'm also experiencing the same issue for iOS. Works fine on desktop. Any progress on this? Or like mentioned a workaround?

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
