### ISSUE TITLE
Feature request : Add support for recurrence

### ISSUE THREAD

**Issue by louia** [AnandChowdhary/calendar-link#475]
It's possible de implement new options to add recurrence to event ? 

Link to RFC Calendar : https://icalendar.org/iCalendar-RFC-5545/3-8-5-3-recurrence-rule.html

**Comment by AnandChowdhary** [comment]
Good idea! Happy to accept a PR :)

**Comment by davidruisinger** [comment]
Unfortunately outlook/office365 and yahoo are not supporting recurring events but for google and ics this should work:
https://github.com/AnandChowdhary/calendar-link/pull/487
