### ISSUE TITLE
Tests that were removed

### ISSUE THREAD

**Issue by tpaulshippy** [AnandChowdhary/calendar-link#491]
I noticed that [ca810d4b955861b0b21cd60d59cb03c2bd16aa4e](https://github.com/AnandChowdhary/calendar-link/commit/ca810d4b955861b0b21cd60d59cb03c2bd16aa4e), [8211ed2eb28f3c441499cc9992a27ad9c1bd5b55](https://github.com/AnandChowdhary/calendar-link/commit/8211ed2eb28f3c441499cc9992a27ad9c1bd5b55) and [cea27e632bd1a0e690fd24b09815dfd57381b9d1](https://github.com/AnandChowdhary/calendar-link/commit/cea27e632bd1a0e690fd24b09815dfd57381b9d1) removed some tests that used to cover the non-Google links. Was something broken? I'm curious why the tests were removed. It doesn't inspire a lot of confidence, to be honest. Thanks!

**Comment by tpaulshippy** [comment]
Went ahead and submitted a PR to bring them back - https://github.com/AnandChowdhary/calendar-link/pull/492

**Comment by AnandChowdhary** [comment]
Aah you're awesome, thanks so much!
