### ISSUE TITLE
Pre-Select Calendar

### ISSUE THREAD

**Issue by vrussillo** [AnandChowdhary/calendar-link#496]
Is there a way to pre-select a specific calendar? 

e.g 

calendar: "TPE Calendar"

![Screen Shot 2022-11-09 at 11 12 35 AM](https://user-images.githubusercontent.com/80196694/200920463-16a02803-b152-4bc7-83ac-dc8b0f85ba19.png)

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
