### ISSUE TITLE
Send a Link to Cancel an Event?

### ISSUE THREAD

**Issue by VikR1000** [AnandChowdhary/calendar-link#502]
With Google/Outlook/Office 365/Yahoo, is it possible to email a link that makes it easy for the recipient to cancel an existing calendar event?

**Comment by AnandChowdhary** [comment]
I think it makes sense to send an updated calendar invitation with the status of canceled. This should do the trick! Here's a StackOverflow answer: https://stackoverflow.com/a/10561761/1656944

**Comment by VikR1000** [comment]
Thanks for the reply! Will an ICS file work to cancel a Google/Outlook/Office 365/Yahoo event? For some reason I had the impression that some or all of those were independent of the ICS file.

**Comment by AnandChowdhary** [comment]
You're right, if one has direct access to the user's calendar (e.g., Google Calendar API), then you can mark an event as canceled. But since this repository uses ICS, I assume that sending an updated ICS file with the "canceled" status should work.

**Comment by VikR1000** [comment]
Okay, thanks!

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
