### ISSUE TITLE
Event time not display on outlook mobile website

### ISSUE THREAD

**Issue by dirkkelderman** [AnandChowdhary/calendar-link#520]
On IOS-Safari for Outlook UvA the start/end times do not come through. Seems that this bug/issue has been reported more often but I'm not sure if there was a solution or workaround provided just yet. If so: please enlighten me!  

<img width="713" alt="Screenshot 2023-01-25 at 12 59 32" src="https://user-images.githubusercontent.com/66555191/214557886-40ff131f-e203-49f2-9dd0-678b98927500.png">

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
