### ISSUE TITLE
Outlook UTC link not working as expected

### ISSUE THREAD

**Issue by duprez** [AnandChowdhary/calendar-link#523]
I am generating a link with UTC format. When I open it from Outlook it should update the hour because I have previously configured Spain timezone in Outlook but Outlook assumes that time is local and creates the event with wrong time.

I tried to send the date according to the documentation:
- Javascript Object Date
- ISO Date
- Unix Timestamp

But unfortunately any of these args don't work as expected. The url formatted never adds the UTC format, always formats the link as a local date. 

**Tested code:**

```
const startDate = moment.utc();

const testJSDate: CalendarEvent = {
    title: 'my title',
    description: 'my description',
    duration: [26, 'minutes'],
    start: startDate.toDate(),
};


const testISO: CalendarEvent = {
    title: 'my title',
    description: 'my description',
    start: startDate.toISOString(),
    duration: [26, 'minutes'],
};

const testUnixTime: CalendarEvent = {
    title: 'my title',
    description: 'my description',
    start: startDate.toDate().getTime(),
    duration: [26, 'minutes'],
};

console.log('Actual UTC date: ', moment.utc().format('DD/MM/YYYY HH:mm:ss'));
console.log('Outlook link with js date: ', outlook(testJSDate));
console.log('Outlook link with ISO date: ', outlook(testISO));
console.log('Outlook link with UNIX timestamp: ', outlook(testUnixTime));
```

**Results:**

```
Actual UTC date:  30/01/2023 13:08:47

Outlook link with js date:  https://outlook.live.com/calendar/0/deeplink/compose?allday=false&body=my%20description&enddt=2023-01-30T13%3A34%3A47&path=%2Fcalendar%2Faction%2Fcompose&rru=addevent&startdt=2023-01-30T13%3A08%3A47&subject=my%20title
Outlook link with ISO date:  https://outlook.live.com/calendar/0/deeplink/compose?allday=false&body=my%20description&enddt=2023-01-30T13%3A34%3A47&path=%2Fcalendar%2Faction%2Fcompose&rru=addevent&startdt=2023-01-30T13%3A08%3A47&subject=my%20title
Outlook link with UNIX timestamp:  https://outlook.live.com/calendar/0/deeplink/compose?allday=false&body=my%20description&enddt=2023-01-30T13%3A34%3A47&path=%2Fcalendar%2Faction%2Fcompose&rru=addevent&startdt=2023-01-30T13%3A08%3A47&subject=my%20title
```

By not indicating that the time is UTC, Outlook interprets it as a local time, which results in a calendar event with the wrong time.

**Expected results**

UTC dates are formatted properly and it’s not assumed that the time is local. Adding a Z to the end of the `startdt` and `enddt` parts of the link works as expected:
 https://outlook.live.com/calendar/0/deeplink/compose?allday=false&body=my%20description&enddt=2023-01-30T13%3A34%3A47Z&path=%2Fcalendar%2Faction%2Fcompose&rru=addevent&startdt=2023-01-30T13%3A08%3A47Z&subject=my%20title

**Information**

- Calendar-link Version 2.4.0
- Moment Version 2.29.4
- OS: Apple M1 13.0.1
- Time zone: CET

**Related issue:** https://github.com/AnandChowdhary/calendar-link/issues/236

**Comment by AnandChowdhary** [comment]
Aah, I see that adding the "Z" makes it clear to Outlook. Happy to accept a PR.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by twalling** [comment]
I'm seeing the same issue. Links for outlook do not include `Z` onto the date time strings and the event's time is set incorrectly over in outlook.
