### ISSUE TITLE
Office 365 deeplink doesn't work, loads forever with console error

### ISSUE THREAD

**Issue by jessewebb** [AnandChowdhary/calendar-link#542]
My users noticed that the Office 365 links no longer work on my site. It appears a change in Microsoft's Office 365 site no longer loads the calendar properly when you use the ```office.com/calendar/0/deeplink/compose``` version of the URL. Instead, the page shows a loading GIF forever and shows an error in the console.

For example, if you try to access this link in a browser with a valid Office 365 login:
https://outlook.office.com/calendar/0/deeplink/compose?path=/calendar/action/compose&rru=addevent&startdt=2023-07-26T16:30:00Z&enddt=2023-07-26T17:30:00Z&subject=Desk%2013&location=Example%20Location&body=&allday=false

You will see the problem where the page never loads and it shows this error in console:
```TypeError: Cannot read properties of undefined (reading 'options')```

![image](https://github.com/AnandChowdhary/calendar-link/assets/64667/1b772458-3258-457a-8288-63666f3373ab)

I found this related post on on the Microsoft tech forums where other users are facing the same issue.
https://techcommunity.microsoft.com/t5/outlook/https-outlook-office-com-calendar-0-deeplink-compose-fails-to/m-p/3816442

In that same thread, they suggest a work-around of changing the URL structure from using ```/calendar/0/deeplink/compose``` to using ```/calendar/action/compose``` which appears to work on Desktop browsers but possibly not mobile devices. I tested this myself and can confirm that using the new URL format does work for my website.

Changing the above broken URL to the working version would look like this:
https://outlook.office.com/calendar/0/deeplink/compose?rru=addevent&startdt=2023-07-26T16:30:00Z&enddt=2023-07-26T17:30:00Z&subject=Desk%2013&location=Example%20Location&body=&allday=false

This bug definitely affects the `office365` function in this library but it may also affect the `outlook` one too. I'm not sure since I  don't have Outlook to test with, but I notice in [the code](https://github.com/AnandChowdhary/calendar-link/blob/master/src/index.ts#L81) that it uses the same `deeplink` URL which is broken in Office 365.

**Comment by M-J-Robbins** [comment]
Hi, I've just hit this issue too. I'm seeing both in Office365 and regular Outlook. 

I can see `action` is working for;
 * Outlook desktop app on Windows
  * Outlook desktop app on Mac
  * Outlook webmail 

  
I can see `deeplink` is working for;
  * Outlook iOS app
  * Android app 

Nothing is supporting both formats 😔

**Comment by AnandChowdhary** [comment]
Thanks for the fix!

**Comment by pklepa** [comment]
PR #543 seems to have fixed this issue. Can we mark this as solved and close it?

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
