### ISSUE TITLE
Outlook removes event subject

### ISSUE THREAD

**Issue by ewl110** [AnandChowdhary/calendar-link#555]
Issue:
Clicking the Microsoft Outlook calendar link populates an event with no subject.

Steps to reproduce:
1. Sign out of any Microsoft accounts
2. Click the Outlook calendar link
3. Get redirected to outlook.live.com and sign-in
4. Event opens in Outlook calendar but is missing a subject line

Additional Notes:
1. Not reproducible if already signed in to a Microsoft account. Subject line populates correctly.
2. Not reproducible if linking directly to outlook.office365.com instead of outlook.live.com. Subject line populates correctly.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
