### ISSUE TITLE
Add type declaration to modern ESM import in package.json

### ISSUE THREAD

**Issue by jnoordsij** [AnandChowdhary/calendar-link#559]
(First of all, thanks for thanks for this handy util package!)

When loading this package with `moduleResolution` set to `bundler` in `tsconfig.json` (see https://www.typescriptlang.org/tsconfig#moduleResolution) an error `TS7016: Could not find a declaration file for module 'calendar-link'.` is raised.

I think (have not been able to test or confirm this yet!) this can be fixed by changing [this line](https://github.com/AnandChowdhary/calendar-link/blob/master/package.json#L9) to
```json
"import": {
    "types": ".dist/index.d.ts",
    "default": "./dist/index.modern.mjs"
},
```
which ensure both TypeScript and import point to the correct file, where currently it tries to find `index.modern.d.ts`.

Relevant docs: https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing.

**Comment by AnandChowdhary** [comment]
Makes sense! Happy to accept a PR :)

**Comment by jnoordsij** [comment]
@AnandChowdhary I opened #560 to resolve this
