### ISSUE TITLE
Yahoo Add to calendar returns HTTP ERROR 400

### ISSUE THREAD

**Issue by ahmadyousefdev** [AnandChowdhary/calendar-link#573]
Hello, when clicking on add to calendar yahoo icon, it takes me to a yahoo page which returns HTTP ERROR 400
is there any fixes for this problem?

thanks

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by AnandChowdhary** [comment]
@ahmadyousefdev were you able to find a URL that works for you? :)

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
