### ISSUE TITLE
location not added when link opened on mobile (iOS)

### ISSUE THREAD

**Issue by truthseekers** [AnandChowdhary/calendar-link#574]
I haven't tested this on android.

Here's my event object:

calendar event:  {
  title: 'Meeting test',
  description: 'description test',
  start: 2023-11-20T23:00:00.000Z,
  duration: [ 2, 'hour' ],
  location: '4505 W Charleston Blvd, Las Vegas, NV, 89102',
  busy: true
}

When I use my web browser (Chrome) on my desktop, and click the event link sent via email, the event shows up in Google Calendar and correctly adds the location to the event.

When I use my iOS device, the location is not added to the event.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by Hughes89** [comment]
I'm also having this issue, looks like it gets dropped then the iOS device opens the google app.

```
const event = {
  "title": "Title",
  "start": startTime
  "end": endTime,
  "location": "151 Place PA, 19128",
  "description": " Details",
  "url": "http://localhost:3000/"
}
```

Generated URL: https://calendar.google.com/calendar/u/0/r/eventedit?dates=20240102T174500Z/20240102T181500Z&details=%3Ca+href%3D%22http://localhost:3000/%22+target%3D%22_blank%22%3E+Details%3C/a%3E&location=151+Place+PA,+19128&text=Title

Works fine in the browser, but when the device opens the Google Cal App it loses the location.

**Comment by AnandChowdhary** [comment]
Aah that's annoying. Any idea how we can circumvent this?

**Comment by YuriiKorovko** [comment]
Same issue

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
