### ISSUE TITLE
Please add the option to enable/disable the In-person toggle button for outlook. 

### ISSUE THREAD

**Issue by MadhukiranMK** [AnandChowdhary/calendar-link#592]
Please add the option to enable/disable the In-person toggle button for outlook.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by AnandChowdhary** [comment]
I'm going to remove this label for now, but I'm not sure how to add this toggle button. Can you please point to any docs for how the URL to behave?

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
