### ISSUE TITLE
Microsoft Teams Deep Links for Calendar Events

### ISSUE THREAD

**Issue by BraedenKilburn** [AnandChowdhary/calendar-link#598]
### Description
I believe the ability to create deep links to Microsoft Teams would be a beneficial addition to the list of available calendar links.

### Reference
For more information on how to create these deep links, please refer to the Microsoft Teams documentation: [Deep Link to Open a Meeting Scheduling Dialog](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-workflow?tabs=teamsjs-v2#deep-link-to-open-a-meeting-scheduling-dialog).

### Contribution
I am willing to look into creating a pull request for this when I have time as well.

**Comment by BraedenKilburn** [comment]
Once #600 is merged, I can go ahead and create a PR for this issue. I'm holding off on creating a PR for this issue until we have working tests first.

**Comment by AnandChowdhary** [comment]
Really appreciate your hard work on this!
