### ISSUE TITLE
Snapshot Tests Failing for ICS Links

### ISSUE THREAD

**Issue by BraedenKilburn** [AnandChowdhary/calendar-link#599]
**Issue Description:**

When running `npm test`, the snapshots for the ics links do not match. There are four main problems causing these mismatches:

1. **Dynamic `DTSTAMP` Property:**
   - The `DTSTAMP` property changes with every test run due to using `dayjs(new Date())`. This leads to snapshots that never match because Jest tests are not configured to use a fixed system time.

2. **Random `UID` Property:**
   - The `UID` property is randomly generated using `Math.random`. Although this is expected behavior for unique IDs, it causes issues with snapshot testing since the value changes every time the test runs.

3. **Line Ending Differences:**
   - On my machine, the properties in the ics link are separated by `%0D%0A` (CRLF) instead of the snapshot's `%0A` (LF) only. This discrepancy is due to the PR change [here](https://github.com/AnandChowdhary/calendar-link/pull/553) where carriage returns were added before the line feeds. It seems the snapshots weren't updated accordingly, which would have been caught if the tests were run before merging.

4. **Missing ICS Properties:**
   - The snapshot is also missing the newly added `PRODID`, which is causing snapshot failures. This property was added in the same PR mentioned above. Updating the snapshots would resolve this issue.

I will help create a PR for these changes.

**Comment by AnandChowdhary** [comment]
Thank you for your PR!
