### ISSUE TITLE
Feature: would you accept if I extend google to support start/end TZ?

### ISSUE THREAD

**Issue by guillenotfound** [AnandChowdhary/calendar-link#607]
I was planning to build a new npm page just for google but since yours does the trick it does not make sense that I do it. Having that said I need to use start/end timezones and I'm not sure if you might want me to provide such PR or since I'm not planning to add it for other providers you prefer not to add it.

Let me know, thanks!

**Comment by AnandChowdhary** [comment]
Happy to!

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
