### ISSUE TITLE
Feature request: support more fields for ICS generation

### ISSUE THREAD

**Issue by aldenquimby** [AnandChowdhary/calendar-link#611]
## Background
- My team is currently using this library for calendar link generation, and [ical-generator](https://github.com/sebbo2002/ical-generator) for `.ics` downloading
- With support for a few additional ics fields here, we could drop that extra library

## ICS Requests
- When `allDay`, add `X-MICROSOFT-CDO-ALLDAYEVENT:TRUE` and `X-MICROSOFT-MSNCALENDAR-ALLDAYEVENT:TRUE` ([see here](https://github.com/sebbo2002/ical-generator/blob/599e4a2e49b2bb9772cc90ff279b8b695dd4dc92/src/event.ts#L1675-L1676C19))
- Add `STATUS:CONFIRMED|TENTATIVE|CANCELLED` field

`ical-generator` supports many additional fields, but none are currently used by my team

If you give me a 👍 that this sounds acceptable, I'd be happy to open a PR with the change

**Comment by AnandChowdhary** [comment]
Sounds like a plan, please feel free to make the PR! :)

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by aldenquimby** [comment]
Commenting to remove stale
