### ISSUE TITLE
ICS files defaulting to all day events

### ISSUE THREAD

**Issue by Paul-Hebert** [AnandChowdhary/calendar-link#78]
Hey, thanks for the great library! 

I'm running into an issue when generating ICS files where all events end up being all day events. It seems to be related to this code:

```js
  const start: string = dayjs(event.start)
    .utc()
    .format(TimeFormats.allDay);
  const end: string = dayjs(event.end)
    .utc()
    .format(TimeFormats.allDay);
```

If I switch `allDay` to `dateTimeUTC` then I get the time info in my ICS file in addition to the day. 

The specification allows using DateTimes as opposed to Dates: https://icalendar.org/iCalendar-RFC-5545/3-3-5-date-time.html

Is there a specific reason these are converted to full day events? Would you like me to open a PR changing the format used?

EDIT: Use source JS for code snippet

**Comment by Paul-Hebert** [comment]
I notice that other functions use this logic: `const format = event.allDay ? TimeFormats.allDay : TimeFormats.dateTimeUTC;`

I'll make a fork and put up a PR with that change

**Comment by Paul-Hebert** [comment]
I just made a PR for this change: https://github.com/AnandChowdhary/calendar-link/pull/80

Let me know if you'd like anything changed. Thanks!

**Comment by AnandChowdhary** [comment]
Hi @Paul-Hebert, thanks for opening this issue! Support for ICS was added very recently in #71, so maybe this error missed my merge review. Perhaps @k4mr4n can have a second look?

Thanks for making the #79 PR too! I'd love to merge it as soon as it's ready. 😄

**Comment by AnandChowdhary** [comment]
@all-contributors can you please add @Paul-Hebert for bugs?
